### ISSUE TITLE
Why deprecated?

### ISSUE THREAD

**Issue by amiri** [metacpan/p5-elasticsearch-model#4]
I was looking for a replacement for Elastic::Model, came across this, and it seemed to fit the bill. Why has this module been deprecated, and do you have recommendations for replacement?

**Comment by mickeyn** [comment]
@amiri the module is not up to date with latest versions of ES and does not really make sense anymore since most functionality is provided through Search::Elasticsearch.

What features are you looking for that you need this one?

**Comment by amiri** [comment]
The features I am looking to retain are the ability to declare documents and their attributes in perl, and thereby to deploy them easily to elasticsearch.
